import { IAvatar } from "./interface";

const PATH = "avatar_";

export const AVATARS: IAvatar[] = [
  {
    id: "aer-dslms-455e",
    src: `${PATH}1`,
    bgColor: "#ffffff",
    x: 10,
    y: 10,
    rotation: -2,
    delay: 0.1,
    scale: 0.8,
  },
  {
    id: "aer-dkllmos-455e",
    src: `${PATH}2`,
    bgColor: "#ffffff",
    x: 40,
    y: 25,
    rotation: -7,
    delay: 0.2,
    scale: 1.0,
  },
  {
    id: "akolmer-dplomlms-745e",
    src: `${PATH}3`,
    bgColor: "#ffffff",
    x: 5,
    y: 65,
    rotation: -5,
    delay: 0.3,
    scale: 0.8,
  },
  {
    id: "a5opr-dl4ms-7o755e",
    src: `${PATH}4`,
    bgColor: "#ffffff",
    x: 80,
    y: 5,
    rotation: 5,
    delay: 0.3,
    scale: 0.9,
  },
  {
    id: "aouiopr-dikllms-7o655e",
    src: `${PATH}5`,
    bgColor: "#ffffff",
    x: 50,
    y: 80,
    rotation: 0,
    delay: 0.7,
    scale: 1,
  },
  {
    id: "aookpr-d756lilms-7ok55e",
    src: `${PATH}6`,
    bgColor: "#ffffff",
    x: 75,
    y: 60,
    rotation: 0,
    delay: 0.8,
    scale: 0.7,
  },
  {
    id: "148-okpr-d756lilms-7ok55e",
    src: `${PATH}7`,
    bgColor: "#ffffff",
    x: 75,
    y: 60,
    rotation: 0,
    delay: 0.8,
    scale: 0.7,
  },
];
