export enum ERoutes {
  "WELCOME" = "home",
  "EDITOR" = "course/editor",
  "HOME" = "dashboard",
  "PREVIEW" = "preview",
  "LEARNERS" = "learners",
  "COURSES" = "courses",
  "COURSE" = "course",
  "REPORTS" = "reports",
  "SIGN" = "sign",
  "DASHBOARD" = "dashboard",
  "PAGE" = "page",
  "COLLABORATION" = "collaboration",
  "SETTINGS" = "settings",
}
